FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake doxygen python-is-python3

COPY . /repo
WORKDIR /repo
RUN make -j8
